# Generated by Django 3.0.1 on 2020-01-09 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_tag', models.CharField(max_length=5, verbose_name='тег игры')),
                ('game_name', models.CharField(max_length=50, verbose_name='название игры')),
                ('pub_date', models.DateField(verbose_name='дата начала игры')),
            ],
        ),
        migrations.CreateModel(
            name='Gamer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gamer_name', models.CharField(max_length=20, verbose_name='имя игрока')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Game')),
            ],
        ),
    ]
