# Generated by Django 3.0.2 on 2020-01-16 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'verbose_name': 'Игра', 'verbose_name_plural': 'Игры'},
        ),
        migrations.AlterModelOptions(
            name='gamer',
            options={'verbose_name': 'Игроки', 'verbose_name_plural': 'Игрок'},
        ),
        migrations.RemoveField(
            model_name='game',
            name='game_tag',
        ),
    ]
