# Generated by Django 3.0.2 on 2020-01-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20200116_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_tag',
            field=models.CharField(default='09uvn', max_length=5, verbose_name='тэг игры'),
        ),
    ]
