# Generated by Django 3.0.2 on 2020-01-16 12:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_game_game_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_present_cost_max',
            field=models.IntegerField(default=1000, verbose_name='максимальная стоимость подарка'),
        ),
        migrations.AddField(
            model_name='game',
            name='game_present_cost_min',
            field=models.IntegerField(default=200, verbose_name='минимальная стоимость подарка'),
        ),
        migrations.AddField(
            model_name='game',
            name='game_timer',
            field=models.IntegerField(default=5, verbose_name='длительность игры'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_name',
            field=models.CharField(default='Игра', max_length=50, verbose_name='название игры'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_tag',
            field=models.CharField(default='S0B2N', max_length=5, verbose_name='тэг игры'),
        ),
        migrations.AlterField(
            model_name='game',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 1, 16, 12, 16, 1, 505762, tzinfo=utc), verbose_name='дата начала игры'),
        ),
    ]
